packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@carbon/icon-helpers'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
publicHoistPattern:
  - esbuild
  - typescript
  - typegraphql-prisma
